using System;
using System.Collections.Generic;
using System.Text;
using PoissonSoft.Crex24Api.Contracts;
using PoissonSoft.Crex24Api.Contracts.Requests;

namespace PoissonSoft.Crex24Api.Trading
{
    /// <summary>
    /// Trading API
    /// </summary>
    public interface ITradingApi
    {
        /// <summary>
        /// Places a new order. The maximum number of active limit orders placed into the orderbook is 100 orders per instrument.
        /// </summary>
        /// <param name="placeOrderRequest"></param>
        /// <returns></returns>
        CrexOrder PlaceOrder(PlaceOrderRequest placeOrderRequest);

        /// <summary>
        /// Returns information about trades generated by the specified order.
        /// </summary>
        /// <param name="orderId">ID of the order for which the information about trades is requested</param>
        /// <returns></returns>
        CrexTrade[] OrderTrades(ulong orderId);

        /// <summary>
        /// Returns the list of active orders with detailed information.
        /// </summary>
        /// <param name="instruments">Optional. Comma-separated list of trade instruments for which the active orders are requested.
        /// If the parameter is not specified, the active orders for all instruments are returned</param>
        /// <returns></returns>
        CrexOrder[] ActiveOrders(string[] instruments = null);

        /// <summary>
        /// Cancels orders with the specified identifiers.
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        ulong[] CancelOrdersById(ulong[] ids);

        /// <summary>
        /// Cancels all orders for each of the specified trade instruments.
        /// </summary>
        /// <param name="instruments">Array of identifiers of trade instruments for which all orders should be cancelled</param>
        /// <returns></returns>
        ulong[] CancelOrdersByInstrument(string[] instruments);

        /// <summary>
        /// Cancels all active orders
        /// </summary>
        /// <returns></returns>
        ulong[] CancelAllOrders();
    }
}
