using System;
using System.Collections.Generic;
using System.Text;
using PoissonSoft.Crex24Api.Contracts;
using PoissonSoft.Crex24Api.Contracts.Requests;

namespace PoissonSoft.Crex24Api.Trading
{
    /// <summary>
    /// Trading API
    /// </summary>
    public interface ITradingApi
    {
        /// <summary>
        /// Places a new order. The maximum number of active limit orders placed into the orderbook is 100 orders per instrument.
        /// </summary>
        /// <param name="placeOrderRequest"></param>
        /// <returns></returns>
        CrexOrder PlaceOrder(PlaceOrderRequest placeOrderRequest);

        /// <summary>
        /// Returns detailed information about the specified order(s).
        /// </summary>
        /// <param name="orderId"></param>
        /// <returns></returns>
        CrexOrder[] OrderStatus(long[] orderId);

        /// <summary>
        /// Returns information about trades generated by the specified order.
        /// </summary>
        /// <param name="orderId">ID of the order for which the information about trades is requested</param>
        /// <returns></returns>
        CrexTrade[] OrderTrades(long orderId);

        /// <summary>
        /// Modifies price and/or volume of an existing order.
        /// </summary>
        /// <param name="orderId"></param>
        /// <param name="newPrice"></param>
        /// <param name="newVolume"></param>
        /// <param name="strictValidation"></param>
        /// <returns></returns>
        CrexOrder OrderModification(long orderId, decimal? newPrice = null, decimal? newVolume = null,
            bool? strictValidation = null);

        /// <summary>
        /// Returns the list of active orders with detailed information.
        /// </summary>
        /// <param name="instruments">Optional. Comma-separated list of trade instruments for which the active orders are requested.
        /// If the parameter is not specified, the active orders for all instruments are returned</param>
        /// <returns></returns>
        CrexOrder[] ActiveOrders(string[] instruments = null);

        /// <summary>
        /// Cancels orders with the specified identifiers.
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        long[] CancelOrdersById(long[] ids);

        /// <summary>
        /// Cancels all orders for each of the specified trade instruments.
        /// </summary>
        /// <param name="instruments">Array of identifiers of trade instruments for which all orders should be cancelled</param>
        /// <returns></returns>
        long[] CancelOrdersByInstrument(string[] instruments);

        /// <summary>
        /// Cancels all active orders
        /// </summary>
        /// <returns></returns>
        long[] CancelAllOrders();

        /// <summary>
        /// Returns the list of trader’s orders with detailed information.
        /// </summary>
        /// <param name="instruments"></param>
        /// <param name="from"></param>
        /// <param name="till"></param>
        /// <param name="limit"></param>
        /// <returns></returns>
        CrexOrder[] OrderHistory(string[] instruments = null, DateTime? from = null, DateTime? till = null,
            ushort? limit = null);

        /// <summary>
        /// Returns the list of trades with detailed information.
        /// </summary>
        /// <param name="instruments"></param>
        /// <param name="from"></param>
        /// <param name="till"></param>
        /// <param name="limit"></param>
        /// <returns></returns>
        CrexTrade[] TradeHistory(string[] instruments = null, DateTime? from = null, DateTime? till = null,
            ushort? limit = null);

        /// <summary>
        /// Returns information about trade commissions: current maker and taker fee rates used in each fee schedule.
        /// These values depend on 30-day trading volume (expressed in BTC) and updated at least once every 24 hours.
        /// </summary>
        /// <returns></returns>
        CrexFeeAndRebate FeeAndRebate();
    }
}
